# Do not apply currently. Not used because node-mesh is enabled.
# metallb is configured to advertise services instead
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: vyos-peer
  namespace: calico-system
spec:
  peerIP: 10.69.100.1
  asNumber: 65001