apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: plex
  labels:
    app: tautulli
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi