apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-smb-pv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/kirito-pool/LongTerm/qbittorrent
    server: kirito.daleajackson.io
    readOnly: false