apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-nfs-pv
spec:
  capacity:
    storage: 58Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/kirito-pool/LongTerm/qbittorrent
    server: kirito.bukkake.cafe
    readOnly: false