apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-nfs-pvc
  namespace: qbittorrent
  labels:
    app: qbittorrent
    kasten-snapshot: exclude
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
  volumeName: qbittorrent-nfs-pv