apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: default
  labels:
    app: qbittorrent
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi