apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-smb-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 100Ti
  volumeName: qbittorrent-smb-pv