apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vash.daleajackson.io
spec:
  selector:
    app: qbittorrent
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: qb-http
    protocol: TCP
    port: 80
    targetPort: 8080