apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: midorima.daleajackson.io
spec:
  selector:
    app: code-server
  type: LoadBalancer
  ports:
  - name: code-server
    protocol: TCP
    port: 80
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  code-server
  namespace: default
  labels:
    app:  code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  code-server
    spec:
      containers:
      - name:  code-server
        image:  linuxserver/code-server:latest
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: 400m
            memory: 1Gi
        env:
        - name: DOCKER_MODS
          value: linuxserver/mods:code-server-python3
        ports:
        - containerPort:  8443
          name:  code-server
        volumeMounts:
        - name: code-server-config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: code-server-config
          persistentVolumeClaim:
            claimName: code-server-config
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/US/Pacific
      restartPolicy: Always