apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-mistlands-world
  namespace: default
  labels:
    app: valheim-mistlands
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-mistlands-server
  namespace: default
  labels:
    app: valheim-mistlands
spec:
  storageClassName: nvme-2repl-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi