apiVersion: v1
kind: Service
metadata:
  name: valheim-mistlands
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mistlands.valheim.daleajackson.io
spec:
  selector:
    app: valheim-mistlands
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: gameport
    protocol: UDP
    port: 42069
    targetPort: 42069 
  - name: queryport
    protocol: UDP
    port: 42070
    targetPort: 42070