apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@bukkake.cafe
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-acme-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              annotations:
                nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0