apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-archiver-scratch-nfs-saitama
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/daleajackson/Desktop/k8s_scratch
    server: 10.1.69.69
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-archiver-scratch-nfs-saitama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 100Ti
  volumeName: data-archiver-scratch-nfs-saitama
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: data-archiver-script
  namespace: default
data:
  entrypoint.sh: |
    #!/bin/bash

    ARCHIVE_FILE=/scratch/$ARCHIVE_FILENAME.tar.gz
    if [[ ! -f "$ARCHIVE_FILE" ]]; then
      PREV_DIR=$(pwd)
      cd /data
      tar --exclude='./lost+found' -czvf $ARCHIVE_FILE .
      cd $PREV_DIR
      echo "Complete!"
    else
      echo "Skipped, $ARCHIVE_FILE exists."
    fi
---
apiVersion: v1
kind: Pod
metadata:
  name:  data-archiver
  namespace: default
spec:
  containers:
  - name:  data-archiver
    image:  ubuntu:latest
    command: [ "/bin/bash", "/entrypoint.sh" ]
    env:
    - name: ARCHIVE_FILENAME
      value: gitlab-logs
    resources:
      requests:
        cpu: "0"
        memory: "0"
      limits:
        cpu: "4"
        memory: 2Gi
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
    - name: data-vol
      mountPath: /data
    - name: scratch-vol
      mountPath: /scratch
    - name: entrypoint-sh
      mountPath: /entrypoint.sh
      subPath: entrypoint.sh
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/US/Pacific
    - name: data-vol
      persistentVolumeClaim:
        claimName: gitlab-logs
    - name: scratch-vol
      persistentVolumeClaim:
        claimName: data-archiver-scratch-nfs-saitama
    - name: entrypoint-sh
      configMap:
        name: data-archiver-script
        items:
          - key: entrypoint.sh
            path: entrypoint.sh
  restartPolicy: Never