apiVersion: v1
kind: Service
metadata:
  name: data-server-nginx
  namespace: default
spec:
  selector:
    app: data-server-nginx
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - name: data-server-nginx
    protocol: TCP
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-default-conf
  namespace: default
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      location /scratch/ {
        alias /scratch/;
        add_header Content-disposition "attachment";
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-server-nginx-scratch
  namespace: default
  labels:
    app: data-server-nginx
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  data-server-nginx
  namespace: default
  labels:
    app:  data-server-nginx
spec:
  selector:
    matchLabels:
      app: data-server-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app:  data-server-nginx
    spec:
      containers:
      - name:  data-server-nginx
        image:  nginx:latest
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "4"
            memory: 2Gi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: data-vol
          mountPath: /data
        - name: scratch-vol
          mountPath: /scratch
        - name: nginx-default-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: code-server-config
        - name: nginx-default-conf
          configMap:
            name: nginx-default-conf
            items: 
            - key: default.conf
              path: default.conf
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/US/Pacific
        - name: scratch-vol
          persistentVolumeClaim:
            claimName: data-server-nginx-scratch

      restartPolicy: Always