apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-loader-scratch-nfs-saitama
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/daleajackson/Desktop/k8s_scratch
    server: 10.1.69.69
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loader-scratch-nfs-saitama
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 100Ti
  volumeName: data-loader-scratch-nfs-saitama
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: data-loader-script
  namespace: default
data:
  entrypoint.sh: |
    #!/bin/bash
    ARCHIVE_FILE=/scratch/$ARCHIVE_FILENAME.tar.gz
    if [[ -f "$ARCHIVE_FILE" ]]; then
      cd /data
      tar -xzvf $ARCHIVE_FILE .
      echo "Complete!"
    else
      echo "Skipped, $ARCHIVE_FILE does not exist."
    fi
    echo Data directory contents:;
    ls -lah /data;
    if [[ ! -z $WAIT_ON_FINISH ]]; then while true; do sleep 30; done; fi
---
apiVersion: v1
kind: Pod
metadata:
  name:  data-loader
  namespace: default
spec:
  containers:
  - name:  data-loader
    image:  ubuntu:latest
    command: [ "/bin/bash", "/entrypoint.sh" ]
    env:
    - name: ARCHIVE_FILENAME
      value: FILENAME_HERE
    # - name: WAIT_ON_FINISH
    #   value: "1"
    resources:
      requests:
        cpu: "0"
        memory: "0"
      limits:
        cpu: "4"
        memory: 2Gi
    volumeMounts:
    - name: data-vol
      mountPath: /data
    - name: scratch-vol
      mountPath: /scratch
    - name: entrypoint-sh
      mountPath: /entrypoint.sh
      subPath: entrypoint.sh
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: TARGET_PVC_NAME_HERE
    - name: scratch-vol
      persistentVolumeClaim:
        claimName: data-loader-scratch-nfs-saitama
    - name: entrypoint-sh
      configMap:
        name: data-loader-script
        items:
          - key: entrypoint.sh
            path: entrypoint.sh
  restartPolicy: Never