apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-plex
  namespace: plex
data:
  promtail.yaml: |
    server:
      disable: true
    clients:
      - url: http://loki-gateway.loki/loki/api/v1/push
    scrape_configs:
      - job_name: plex-logs
        pipeline_stages:
          - regex:
              source: filename
              expression: '.*/(?P<filename>.*)'
          - labels:
              filename:
        static_configs:
          - labels:
              job: plex-logs
              app: plex
              __path__: "/config/plex-volume/Library/Application Support/Plex Media Server/Logs/*[^.1-9].log"
      - job_name: plex-plugin-logs
        pipeline_stages:
          - regex:
              source: filename
              expression: '.*/(?P<filename>PMS Plugin Logs/.*)'
          - labels:
              filename:
        static_configs:
          - labels:
              job: plex-plugin-logs
              app: plex
              __path__: "/config/plex-volume/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"