apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: default
  labels:
    app: plex
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: default
  labels:
    app: plex
    kasten-snapshot: exclude
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  labels:
    app: plex
    kasten-snapshot: exclude
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 100Ti
  volumeName: plex-media-pv