apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: acme-challenge-allow
  namespace: kasten-io
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0