apiVersion: v1
kind: PersistentVolume
metadata:
  name: k10-backup-kirito-pv
spec:
  capacity:
    storage: 58Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/kirito-pool/backups
    server: kirito.daleajackson.io