apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k10-backup-kirito
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 100Ti
  volumeName: k10-backup-kirito-pv