apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: vyos-peer
  namespace: metallb
spec:
  myASN: 65003
  peerASN: 65001
  peerAddress: 10.1.69.254
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
  namespace: metallb