apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-certs
  namespace: default
type: Opaque
stringData:
  asuna.daleajackson.io.crt: |
    subject=C = US, ST = Washington, L = Seattle, CN = Asuna

    issuer=DC = io, DC = daleajackson, CN = BUKKAKE-Internal-CA

    -----BEGIN CERTIFICATE-----
    MIIF9TCCBN2gAwIBAgITKgAAAEYqab6ckH3GKwAAAAAARjANBgkqhkiG9w0BAQsF
    ADBQMRIwEAYKCZImiZPyLGQBGRYCaW8xHDAaBgoJkiaJk/IsZAEZFgxkYWxlYWph
    Y2tzb24xHDAaBgNVBAMTE0JVS0tBS0UtSW50ZXJuYWwtQ0EwHhcNMjIwNTI5MDgy
    MzM5WhcNMjQwNTI4MDgyMzM5WjBEMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
    aGluZ3RvbjEQMA4GA1UEBxMHU2VhdHRsZTEOMAwGA1UEAxMFQXN1bmEwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4n2nCPAis/fOtL2B7jS21TQDUrjoV
    rihJfYcMPU+1w9rJSJGonCkjCYyEf6DLaO51asfEql9HLLrN1y6tcHB9Bem/1d0z
    0f5mxCLN2yWbT7kIS/ai3wNj//01epoiuhDQ2YYTUDn8qHgRXZVI7H3GfaecqQyj
    DArHw+MhMHKqEMLgeM5+YgpCifzz8Ad9r71BxWQpIdIb2tPN4+FCaAhq/y/HWcYJ
    8LsCIKFrhEKe63GP8UWuFem/WzhsOfXYbkbpoXuFg/dNHL1XYHb9LnWdwSllJgRu
    fkmU7Woah4TehURXcs2aTeZmoAxvxI6DaIuR22zyPpqf+Juvv/x9n2pXAgMBAAGj
    ggLSMIICzjCBoQYDVR0RBIGZMIGWghVhc3VuYS5kYWxlYWphY2tzb24uaW+CHnJl
    Z2lzdHJ5LmFzdW5hLmRhbGVhamFja3Nvbi5pb4IuZ2l0bGFiLmRlZmF1bHQuc3Zj
    LmJ1a2tha2UuazhzLmRhbGVhamFja3Nvbi5pb4ItZ2l0bGFiLmdpdGxhYi5zdmMu
    YnVra2FrZS5rOHMuZGFsZWFqYWNrc29uLmlvMB0GA1UdDgQWBBSEwqk280gtGtGi
    WaWwnbzrYux5fzAfBgNVHSMEGDAWgBQoKgdRf7z3Cv/2X8pX/mnzv7tgADCB0wYD
    VR0fBIHLMIHIMIHFoIHCoIG/hoG8bGRhcDovLy9DTj1CVUtLQUtFLUludGVybmFs
    LUNBLENOPU9LQUJFLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxD
    Tj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWRhbGVhamFja3NvbixEQz1p
    bz9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JM
    RGlzdHJpYnV0aW9uUG9pbnQwgckGCCsGAQUFBwEBBIG8MIG5MIG2BggrBgEFBQcw
    AoaBqWxkYXA6Ly8vQ049QlVLS0FLRS1JbnRlcm5hbC1DQSxDTj1BSUEsQ049UHVi
    bGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlv
    bixEQz1kYWxlYWphY2tzb24sREM9aW8/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVj
    dENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwIQYJKwYBBAGCNxQCBBQeEgBX
    AGUAYgBTAGUAcgB2AGUAcjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYB
    BQUHAwEwDQYJKoZIhvcNAQELBQADggEBANqP8gVH0PeWqlNcQLIb/PcMDFTg0j8s
    YJQV0NLnGSz+DmxDS+QGsX10iHdBEtsMRTL+iFhH3OeVfTCw/2TPi0O1iSJ6r/Hb
    CXtUsD7ynPq44BPi7TujiJCrvLzaOCwuTp7kqF2F7ge/otbdxisFQXjOxUkhBD+2
    G0JT5LY7BlrDb1FazwQqPa8wtkt32G/rrqfniakRfWDPbKDZkZNHlySopYmIzXQw
    BPxv3jt91wDtOrG9c1877fLvajpJKbRKnjNr8Wmx9K40ZKga7qZuzYTRNjvNtOvE
    VwNhLzgyJM5Jw2ssZo6Vhr/oeOqqw9ZR2eW6Te89v0TwuWcrqwdoP3U=
    -----END CERTIFICATE-----

    subject=DC = io, DC = daleajackson, CN = BUKKAKE-Internal-CA

    issuer=DC = io, DC = daleajackson, CN = BUKKAKE-Internal-CA

    -----BEGIN CERTIFICATE-----
    MIIDezCCAmOgAwIBAgIQFg1l/0uD6aFGVMPL3KyCaTANBgkqhkiG9w0BAQsFADBQ
    MRIwEAYKCZImiZPyLGQBGRYCaW8xHDAaBgoJkiaJk/IsZAEZFgxkYWxlYWphY2tz
    b24xHDAaBgNVBAMTE0JVS0tBS0UtSW50ZXJuYWwtQ0EwHhcNMTkwMjA0MDI0MjQ3
    WhcNMjkwMjA0MDI1MjQ2WjBQMRIwEAYKCZImiZPyLGQBGRYCaW8xHDAaBgoJkiaJ
    k/IsZAEZFgxkYWxlYWphY2tzb24xHDAaBgNVBAMTE0JVS0tBS0UtSW50ZXJuYWwt
    Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDmPQMxa9bEXPTHAlw9
    GE37Dkkv565F0I6LXR/uZNzVs43d++u48lxomUFiZM07Z6YCA70EtQOkRYsOLQWF
    D1/LLe9zp1FFjziMtkkbiqtk33LjbR9EsssBigiDjZ3pO9tfUM8vIsABIVhUwozL
    Whcr4RkpqrJ1RczYRSLRbmatcVrMOb498qg4vJHTPwY1TsncbPulhY3c9SbMn+b1
    hGPddJZxSg+Z84Q+ssJYWd49AVeur1KenX6dx0zh0i2pjdZ9c/eZ5OoYskm+vYW8
    f+4Rjx3ZzuY78F/mo+YJtx8MGrnAVYc5LqcC360AuJmHSl6x8NASkSC1jOB1o4Ir
    9UktAgMBAAGjUTBPMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
    DgQWBBQoKgdRf7z3Cv/2X8pX/mnzv7tgADAQBgkrBgEEAYI3FQEEAwIBADANBgkq
    hkiG9w0BAQsFAAOCAQEAMQMfK67V5H4toppP2mMTCT+xCVYjMB2HTcqV8wMK47cT
    TcC0HCQJRHge3aCToqMMJd69NmPSmHe6x+r5nX+Ld89D+Eo554D9Y38U00GhLK10
    Utz0F36kblOJtzNdBufxFmW85gscK7ecLDPH/S9iFawIOofCgsmCeDn/a6yftm/Q
    ZGfhv8VfgfTc2unVFMPUGK2DJgJiWy0G6Y7Okw6GLBklvybPnrh88ezRwS4R6XvD
    cdpnPaqIhGjTgGRYdlsb3QgOvxc3WL+BsMISMQdZ6a1Y44AycIDh5WBwSsuPNNat
    DYxFYJ22G82xvEnuSjKlJ4TdpQf2IRQjFbMyHkIM3w==
    -----END CERTIFICATE-----
