kind: ConfigMap
apiVersion: v1
metadata:
  name: gitlab-omnibus-config-map
  namespace: default
data:
  omnibus-config: |
    external_url 'https://asuna.daleajackson.io'
    gitlab_kas['enable'] = true

    ###########################
    # SSL
    ###########################
    letsencrypt['enable'] = false
    nginx['redirect_http_to_https'] = true

    ###########################
    # Container Registry
    ###########################
    registry_external_url 'https://registry.asuna.daleajackson.io'
    registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/asuna.daleajackson.io.crt"
    registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/asuna.daleajackson.io.key"

    registry['storage'] = {
      's3' => {
        'accesskey' => 'gitlab',
        'secretkey' => 'pQ7YREY60RTrXYX1olsBBfX',
        'bucket' => 'asuna-gitlab-container-registry',
        'region' => 'bukkake',
        'regionendpoint' => 'https://yuno.daleajackson.io',
        'pathstyle' => true
      }
    }

    ###########################
    # Memory tuning (reduction)
    ###########################
    prometheus_monitoring['enable'] = false
    sidekiq['max_concurrency'] = 10
    puma['worker_processes'] = 0

    gitaly['ruby_max_rss'] = 200_000_000
    gitaly['concurrency'] = [
      {
        'rpc' => "/gitaly.SmartHTTPService/PostReceivePack",
        'max_per_repo' => 3
      }, {
        'rpc' => "/gitaly.SSHService/SSHUploadPack",
        'max_per_repo' => 3
      }
    ]

    # gitaly['cgroups_count'] = 2
    # gitaly['cgroups_mountpoint'] = '/sys/fs/cgroup'
    # gitaly['cgroups_hierarchy_root'] = 'gitaly'
    # gitaly['cgroups_memory_enabled'] = true
    # gitaly['cgroups_memory_limit'] = 500000
    # gitaly['cgroups_cpu_enabled'] = true
    # gitaly['cgroups_cpu_shares'] = 512

    gitaly['env'] = {
      'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'
    }

    # Old config for moving SSH when already in use on the same IP
    # gitlab_rails['gitlab_shell_ssh_port'] = 2220