apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: asuna.daleajackson.io
spec:
  selector:
    app: gitlab
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: gitlab-ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: gitlab-http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: gitlab-https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gitlab
  namespace: default
  labels:
    app:  gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  gitlab
    spec:
      containers:
      - name:  gitlab
        image:  gitlab/gitlab-ce:15.5.1-ce.0
        resources:
          requests:
            cpu: 100m
            memory: 4.5Gi
          limits:
            cpu: "2"
            memory: 8Gi
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: from_file('/configmap/omnibus_config.rb')
        ports:
        - containerPort: 443
          name: gitlab-https
        - containerPort: 80
          name:  gitlab-http
        - containerPort: 22
          name: gitlab-ssh
        volumeMounts:
        - name: config
          mountPath: /etc/gitlab
        - name: data
          mountPath: /var/opt/gitlab
        - name: logs
          mountPath: /var/log/gitlab
        - name: omnibus-config
          mountPath: /configmap
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: gitlab-config
        - name: data
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: logs
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: omnibus-config
          configMap:
            name: gitlab-omnibus-config-map
            items:
            - key: omnibus-config
              path: omnibus_config.rb
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/US/Pacific
      restartPolicy: Always