apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: default
  labels:
    app: gitlab
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: default
  labels:
    app: gitlab
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
  namespace: default
  labels:
    app: gitlab
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi