(import 'dashboards/direct-use.libsonnet')
+ (import 'dashboards/ceph.libsonnet')
+ (import 'dashboards/loki.libsonnet')
+ (import 'dashboards/mimir.libsonnet')
+ (import 'dashboards/truenas.libsonnet')