ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: nginx
  tls:
    - hosts:
      - HOSTNAME_REPLACE_KEY
      secretName: grafana-tls
  hosts:
  - HOSTNAME_REPLACE_KEY
persistence:
  enabled: true
admin:
  existingSecret: grafana-auth