apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-data
  namespace: bind-dns
  labels:
    app: bind-data
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi