apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  namespace: bind-dns
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.2.69.10
  labels:
    app: bind9
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: bind9
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
    name: bind9-tcp
  - protocol: UDP
    port: 53
    targetPort: 53
    name: bind9