ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: kise.bukkake.cafe
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - kise.bukkake.cafe
      secretName: gitea-tls

postgresql:
  enabled: true
  auth: 
    enablePostgresUser: false
    existingSecret: gitea-db-auth

gitea:
  admin:
    existingSecret: gitea-admin-auth
  additionalConfigFromEnvs:
  - name: GITEA__DATABASE__PASSWD
    valueFrom:
      secretKeyRef:
        name: gitea-db-auth
        key: password

persistence:
  create: false
  claimName: data-gitea-0

postgresql-ha:
  enabled: false