clusterDomain: weebcluster.k8s.daleajackson.io

ingress:
  enabled: true
  className: nginx-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: asuna.bukkake.life
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - asuna.bukkake.life
      secretName: gitea-tls

postgresql:
  auth: 
    enablePostgresUser: false
    existingSecret: gitea-db-auth

gitea:
  admin:
    existingSecret: gitea-admin-auth
  additionalConfigFromEnvs:
  - name: ENV_TO_INI__DATABASE__PASSWD
    valueFrom:
      secretKeyRef:
        name: gitea-db-auth
        key: password