ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: nginx
  tls:
    - hosts:
      - grafana.bukkake.cafe
      secretName: grafana-tls
  hosts:
  - grafana.bukkake.cafe
persistence:
  enabled: true
admin:
  existingSecret: grafana-auth