global:
  persistence:
    storageClass: nvme-rook-ceph

ingress:
  create: true
  class: nginx
  tls:
    enabled: true
    secretName: k10-dashboard-tls
  host: k10.bukkake.cafe
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/app-root: /k10

auth:
  basicAuth:
    enabled: true
    secretName: k10-dashboard-htpasswd