loki:
  auth_enabled: false # Disables multi-tenancy -- https://grafana.com/docs/loki/latest/operations/multi-tenancy/
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: https://yuno.bukkake.cafe
      s3ForcePathStyle: true
      # Loki's Helm chart doesn't support providing a Secret for these values...
      # They are set using a separate values file during the chart install.
      # accessKeyId: "something"
      # secretAccessKey: "something"

# Promtail is installed and will scrape logs instead
test:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

gateway:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/client-body-buffer-size: 1M
    hosts:
    - host: loki.bukkake.cafe
      paths: 
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - loki.bukkake.cafe
      secretName: loki-gateway-tls