configmap:
  enabled: true
config:
  clients:
  - url: http://loki-gateway/loki/api/v1/push
    batchwait: 10s
  snippets:
    extraScrapeConfigs: |
      - job_name: node-systemd-journal
        journal:
          labels:
            job: 'node-systemd-journal'
          path: /var/log/host/journal
        relabel_configs:
        - source_labels:
          - __journal__systemd_unit
          target_label: systemd_unit
        - source_labels:
          - __journal__hostname
          target_label: node
    extraRelabelConfigs:
      - source_labels: ['__meta_kubernetes_pod_node_name']
        target_label: '__host__'

extraVolumes:
- name: journal
  hostPath:
    path: /var/log/journal
- name: machine-id
  hostPath:
    path: /etc/machine-id

extraVolumeMounts:
- name: journal
  mountPath: /var/log/host/journal
  readOnly: true
- name: machine-id
  mountPath: /etc/machine-id
  readOnly: true