apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: "2023-09-10T09:00:18Z"
  generation: 6
  name: yuno
  namespace: minio-yuno
  resourceVersion: "144742255"
  uid: d370b78a-dba6-4bb6-9366-b9481df78cc7
scheduler:
  name: ""
spec:
  configuration:
    name: yuno-env-configuration
  credsSecret:
    name: yuno-secret
  exposeServices: {}
  features:
    domains:
      console: https://yuno-console.waifus.dev
      minio:
      - https://yuno.waifus.dev
      - https://yuno.bukkake.cafe
  image: minio/minio:RELEASE.2023-09-07T02-05-02Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - yuno
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources:
      requests:
        cpu: "0"
        memory: 2Gi
    runtimeClassName: ""
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: Always
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 3
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1099511627776"
        storageClassName: nvme-2repl-rook-ceph
      status: {}
    volumesPerServer: 2
  requestAutoCert: false
  users:
  - name: yuno-user-0