apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  namespace: default
  annotations:
    #nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    nginx.ingress.kubernetes.io/client-body-buffer-size: 200M
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - photos.bukkake.life
    secretName: photoprism-tls
  ingressClassName: nginx-external
  rules:
  - host: photos.bukkake.life
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: photoprism
            port:
              number: 80