apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
  namespace: default
  labels:
    app: photoprism-storage
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-mariadb
  namespace: default
  labels:
    app: photoprism-mariadb
spec:
  storageClassName: nvme-rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi