apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: objectify-me-daddy
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: nvme
  dataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: nvme
  gateway:
    port: 80
    instances: 1
    placement:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              rgw: objectify-me-daddy
          topologyKey: kubernetes.io/hostname
